void foo_float(float bar);
void foo_double(double bar);
void foo_long_double(long double bar);
void foo_int(int bar);
void foo_unsigned_int(unsigned int bar);
void foo_signed_int(signed int bar);
void foo_short(short bar);
void foo_unsigned_short(unsigned short bar);
void foo_signed_short(signed short bar);
void foo_long(long bar);
void foo_unsigned_long(unsigned long bar);
void foo_signed_long(signed long bar);
void foo_long_long(long long bar);
void foo_unsigned_long_long(unsigned long long bar);
void foo_signed_long_long(signed long long bar);
void foo_char(char bar);
void foo_unsigned_char(unsigned char bar);
void foo_signed_char(signed char bar);
