name: Running Unit Tests

on:
  push:
    branches:
      - full_header_support


jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: get clang installer
        run: wget https://apt.llvm.org/llvm.sh

      - name: make installer runable
        run: chmod +x llvm.sh

      - name: install clang
        run: sudo ./llvm.sh 17

      - name: install python dependencies
        run: pip install clang pyyaml

      - name: install ruby
        run: sudo apt install ruby -y

      - name: install ruby dependencies
        run: sudo gem install yaml cast-to-yaml

      - run: cd /usr/lib/x84_64-linux-gnu
      - run: ln -s libclang-17.so.1 libclang-17.so

      - name: checkout repo
        uses: actions/checkout@v4

      - name: run test
        run: |
          ret=0
          for header in ./unit_tests/*.h; do
            echo $header
            ruby emit_yaml.rb $header > ruby.out
            python3 Clang/parser.py $header > ts.out
            diff ruby.out ts.out
            ret +=$?
          done
          exit(ret)